name: "Issuetron-3000"
description: "A GitHub action to turn on a light in the physical world when someone opens an issue on your repo"
inputs:
  time:
    description: "How much time we will keep the light on (in seconds)"
    required: true
    default: "10"
  blink:
    description: "Would you like to enable blinking?"
    required: false
    default: "true"
  io_username:
    description: "Your Adafruit IO username"
    required: false
  io_key:
    description: "Your Adafruit IO key"
    required: false
  io_dashboard:
    description: "Your Adafruit dashboard name"
    required: false
outputs:
  success:
    description: "We will inform you if we were able to reach your IoT device"
runs:
  using: "node12"
  main: "dist/index.js"
